// src/bVue/BLoading.vue
<template>
    <div class="mesh-loader">
        <div class="set-one">
            <div class="circle bg-warning"></div>
            <div class="circle bg-info"></div>
        </div>
        <div class="set-two">
            <div class="circle bg-secondary"></div>
            <div class="circle bg-primary"></div>
        </div>
    </div>
</template>

// src/bReact/BLoading.tsx
export default function BLoading() {
    return (
        <div className="mesh-loader">
            <div className="set-one">
                <div className="circle bg-warning"></div>
                <div className="circle bg-info"></div>
            </div>
            <div className="set-two">
                <div className="circle bg-secondary"></div>
                <div className="circle bg-primary"></div>
            </div>
        </div>
    )
}
